laminas/getlaminas.org

- src/App/Handler/HomePageHandler.php
- src/App/Handler/HomePageHandlerFactory.php
- test/AppTest/Handler/HomePageHandlerFactoryTest.php
- test/AppTest/Handler/HomePageHandlerTest.php
Like other handlers, the HomePageHandler only require `TemplateRendererInterface` instance.
> clean up HomePageHandler dependencies

- src/Blog/templates/list.phtml
- src/Blog/templates/post.phtml
- templates/about/overview.phtml
- templates/community/participate.phtml
Fixes negative margins on headlines:
Fixed:
> add missing col element for headlines within row

- templates/layout/default.phtml
I think it is better to have link here to the docs.laminas.dev instead getlaminas.org.
> Change link to "Components and MVC"

- .platform.app.yaml
- README.md
- composer.json
- composer.lock
- config/autoload/global.php
- config/config.php
- config/routes.php
- docker-compose.yml
- src/ReleaseFeed/Author.php
- src/ReleaseFeed/ConfigProvider.php
- src/ReleaseFeed/DisplayFeedHandler.php
- src/ReleaseFeed/DisplayFeedHandlerFactory.php
- src/ReleaseFeed/ReceiveFeedItemHandler.php
- src/ReleaseFeed/ReceiveFeedItemHandlerFactory.php
- src/ReleaseFeed/Release.php
- src/ReleaseFeed/Releases.php
- src/ReleaseFeed/VerifyTokenMiddleware.php
- src/ReleaseFeed/VerifyTokenMiddlewareFactory.php
- templates/layout/default.phtml
- templates/releases.rss
This patch adds functionality for both displaying and updating the release feed.
The release feed will be updated via the API endpoint `/api/release`, which expects a JSON-encoded document to be submitted using the method POST, and containing the following keys:
- author_name (string)
- author_url (string)
- changelog (string)
- package (string)
- publication_date (RFC-formatted date-time string)
- url (string)
- version (string)
It will use that functionality to update the feed present in `data/cache/releases.rss`.
To safeguard this API, we will need to create a token and store it in the hosting environment; the API verifies that the token is present in the incoming request, and, if not, returns a 401 response.
The path `/releases/rss.xml` will serve the file `data/cache/releases.rss`. …
> feat: display and update release feeds

- data/blog/2020/2020-03-09-transferring-zf-to-laminas.md
- src/Blog/BlogAuthor.php
- src/Blog/BlogPost.php
- src/Blog/Console/FeedGenerator.php
- src/Blog/Console/SeedBlogDatabase.php
- src/Blog/CreateBlogPostFromDataArray.php
- src/Blog/PlatesFunctionsDelegator.php
- src/Blog/templates/post.phtml
Adds a new class, `BlogAuthor`. When creating a `BlogPost`, any class that composes the `CreateBlogPostFromDataArray` trait will pull author metadata from the appropriate YAML file and use it to create and compose a `BlogAuthor` instance as a property of `BlogPost`. If no metadata is found, it uses only the username, with the email address no-reply@getlaminas.org.
Code for seeding the database and creating RSS feeds has been updated to reflect the changes.
> Link blog posts to their authors

- src/Security/Handler/SecurityHandler.php
The date created/modified values used top populate the feed are strings in RFC format; however, laminas-feed expects `DateTimeInterface` instances. This patch casts those values to `DateTimeImmutable` when populating the feed and feed entries.
Fixes #39
> Ensure we pass DateTimeInterface instances to feeds

- src/Blog/ConfigProvider.php
- src/Blog/Handler/FeedRedirectHandler.php
- src/Blog/Handler/FeedRedirectHandlerFactory.php
Per laminas/documentation-theme#38, we currently have published feed URLs to the wrong locations.
Until we rebuild all docs, it would be best if we redirect these to the correct location. Once we have, we can remove this functionality.
> Redirect incorrect feed URLs to proper locations

- bootstrap/scss/_custom-variables.scss
- templates/app/home-page.phtml
- templates/layout/default.phtml
Signed-off-by: Michael Bourquin <mbourquin@devprod.com>
| Documentation | yes
The goal of this PR is to **improve the positioning and visibility of laminas.org website** by adding some (basic) SEO enhancements for terms like PHP, framework, enterprise.
- Important terms like "PHP Framework" was missing in the meta title. I just propose to add it by default in each meta title.
- I also added the term "Enterprise", the final part of the meta title will be  **- Laminas Project - Enterprise PHP Framework**
- I also modified the main H1 in the home page to include principals terms, final H1 will be **Laminas Project, the enterprise-ready PHP …
> Added basic search engine optimization + enabled responsive fonts

- .docker/php/Dockerfile
- .platform.app.yaml
- README.md
- composer.json
- composer.lock
While PHP 7.3 is still supported on Platform.sh, I'm not sure how much longer it will be. Since I need to do a content update today, I've updated the site to run on PHP 8.0:
- Bumped the PHP requirement and platform PHP in `composer.json` to `~8.0.0`.
- Updated dependencies in `composer.json` to have minimums that work with PHP 8.
- Updated the development docker image to use PHP 8.
- Updated the Platform.sh configuration to use PHP 8. It also bumps to Composer v2, and removes hirak/prestissimo (as it conflicts with Composer v2).
> Update to PHP 8.0

- composer.json
- composer.lock
This plugin conflicts with latest `composer/composer` releases, and is not used inside
this repo as per https://github.com/laminas/getlaminas.org/pull/106#issuecomment-1207595866
| Bugfix        | no
| QA            | yes
> Removed unused `laminas/laminas-dependency-plugin`

- templates/app/home-page.phtml
The rows come with negative margins:
https://getbootstrap.com/docs/4.6/layout/grid/#how-it-works
> Adds missing container for grid with logos to prevent negative margins

- .platform.app.yaml
- bootstrap/build.sh
- bootstrap/build/.gitignore
- bootstrap/gulpfile.mjs
- bootstrap/package-lock.json
- bootstrap/package.json
gulp-rev-all v4 has converted to ESM format. To accommodate the upgrade gulpfile is converted to ESM as well.
anchor-js is bumped to v5 but I was not able to verify if there are any problems. I am not sure where it is used.
This also includes few QA changes:
- convert package.json to be our own rather than starter kit
- drop unused build script from start kit
- bump minor node version
Supersedes #131 and #133
> Upgrade frontend tools

- .platform.app.yaml
Composer 2.6 allows symfony/console v7 but is not compatible with it. Since console released last week builds are failing.
Downgrade composer to 2.5 until 2.7 was released with proper support.
> Downgrade composer to 2.5 until 2.7

- data/blog/2024/2024-03-08-summary-of-the-meeting-in-march-2024.md
A new blog post has been added which summarizes the March 2024 meeting of the Laminas Project Technical Steering Committee. Topics covered include maintenance decision visibility, and the optional dependency of laminas-servicemanger in certain components.
> Add March 2024 meeting summary blog post

- .platform.app.yaml
- bootstrap/scss/_custom-styles.scss
- composer.json
- psalm-baseline.xml
- src/App/ConfigProvider.php
- src/App/Console/WriteRepositoryData.php
- src/App/Handler/CustomPropertiesHandler.php
- src/App/Handler/CustomPropertiesHandlerFactory.php
- templates/app/packages-custom-properties.phtml
@arhimede Here is the requested initial version of the custom property listing page and its command to generate and save a json file containing the relevant data. You will require setting up the "REPO_TOKEN" variable on the staging environment in platform.sh to allow the calls to the github API.
The page is only accessible via url, via the "/packages-custom-properties" route.
For now, repository properties are simply displayed as a key-value pair, with the possibility of adding shield.io badges using dynamic badges such as ![Dynamic JSON Badge](https://img.shields.io/badge/dynamic/json?url=https%3A%2F%2Fapi.github.com%2Frepos%2Flaminas%2Flaminas-mail%2Fproperties%2Fvalues&query=%24%5B%3F(%40.property_name%3D%3D%22is-deprecated%22)%5D.value&label=is-deprecated).
The issue with displaying …
> initial property listing page and data generation command

- bootstrap/scss/_custom-styles.scss
- src/App/Console/WriteRepositoryData.php
- templates/app/packages-custom-properties.phtml
- templates/partials/navigation.phtml
@arhimede added a legend for the "maintenance-mode" property on the listing page, included said listing page in the navbar. "Maintenance mode minutes" properties now link to the relevant file on github. 
Replaced the "exceptions array" with a package name filter
> Added maintenance-mode legend, minutes links

- .docker/php/Dockerfile
- README.md
Instead of installing PHP extensions via `apk` _(Which fails)_, use `mlocati/docker-php-extension-installer`
Also fix missing step in README that causes `composer build` to fail
> Fix: Docker container does not build locally

- templates/partials/navigation.phtml
A potential fix for issue #191 which was triggered by calling `$this->url()` when accessing a nonexistent route. The resulting exception would prevent rendering of the 404 page, so the straightforward solution was to catch the exception in the partial itself.
> display 404 page on invalid URL

- .github/workflows/no-pr-to-live.yml
- .github/workflows/publish.yml
To ensure no changes have skipped staging only fast forward pushes from staging should be used.
This PR adds protection workflow that together with branch protection rule blocks all PRs to master branch.
Additional workflow is added that performs fast forwarding push and can be triggered via web ui via workflow dispatch.
> Add protections against PRs to live branch and add publish workflow

- .github/workflows/commit-in-staging.yml
- .github/workflows/pr-autocloser.yml
Branch protection rules do not work exactly the way I expected them to. They block PR and they block push.
So, here is the better alternative to ensure all changes go through staging.
This workflow introduces a dummy check that runs only in staging branch and marks te commit for the branch protection rule for the master branch. That means commit that was not at the HEAD of the staging branch can not be pushed to the master.
Now, with this check in place there are two flows that can't be used together:
- fast forwarding push. Can be done via cli with `git fetch upstream && git push upstream upstream/staging:master` or via workflow dispatch to the workflow doing the same.
- pull request. Once pull request is merged history is no longer fast forwardable. All updates from staging to master …
> Add staging branch check for branch protection rules

- .github/workflows/pr-autocloser.yml
gh cli wants web url and I used API url for the PR.
Use repo and number instead as it is more reliable for scripted usage
> Fix wrong PR url from GHA context. Improve close comment verbiage

- .markdownlint.json
- data/blog/2024/2024-11-18-october-news.md
> fix missing extend tag.

- bootstrap/gulpfile.mjs
- bootstrap/js/base.js
- bootstrap/package.json
- bootstrap/scss/_custom-styles.scss
- src/App/ContentParser/Parser.php
- src/Blog/BlogPost.php
- src/Blog/CreateBlogPostFromDataArray.php
- src/Blog/templates/post.phtml
Introduced Table of Contents parsing and rendering functionality in blog posts. Updated `BlogPost` model, `CreateBlogPostFromDataArray` class, and the template to include and display the TOC. Adjusted heading level configuration to ensure deeper heading levels are included in the TOC generation.
References:
- https://commonmark.thephpleague.com/2.6/extensions/table-of-contents/
- https://commonmark.thephpleague.com/2.6/extensions/heading-permalinks/
> Add support for rendering Table of Contents in blog posts

- src/App/ContentParser/Parser.php
Updated the `Parser.php` class to include a `blockquote` CSS class for rendering blockquote elements.
- https://getbootstrap.com/docs/5.3/content/typography/#blockquotes
- https://commonmark.thephpleague.com/2.7/extensions/default-attributes/
Closes #277
> Add blockquote styling for content parsing

- composer.json
- composer.lock
- renovate.json
Clearly, renovate with this config does not work as expected. Reset it to basic config as in other repositories.
PHP in platform config is not grouped with php in composer.json
`bump` is used instead of `replace` strategy for php. `automergeDisabled` preset is overridden too.
> Revert renovate config to default
