laminas/getlaminas.org

src/App/Handler/HomePageHandler.php

No need of the default Expressive skeleton stuff in the HomePageHandler.

Remove unused template variables on the homepage

---

bootstrap/gulpfile.js

During building the docker image Gulp version 4 is installed. gulpfile.js have to be migrated to this new version.

Modified gulpfile.js to be compatible with Gulp 4

---

.docker/bin/compose-entrypoint
.docker/bin/php-entrypoint
.gitignore
Dockerfile
bootstrap/gulpfile.js
docker-compose.yml

docker-compose build and docker-compose up give many errors. With this branch is possible to create the image and run it with docker-compose.
Modifications:
- .env file is not used, I removed it from docker-compose.yml
- generated asserts have not to be placed in mapped folders.
This resolve:
- https://github.com/laminas/getlaminas.org/issues/4
- https://github.com/laminas/getlaminas.org/issues/5

Fix error building image with docker compose

---

templates/community/participate.phtml

|    Q        |   A
|------------ | ------
| Bugfix      | yes
| BC Break    | no
| New Feature | no
| RFC         | no
Our discourse has moved to https://discourse.laminas.dev :tada:

Discourse has moved

---

src/Blog/Handler/ListPostsHandler.php
src/Blog/templates/list.phtml
src/Blog/templates/post.phtml

Adapts the default page layout for blog and blog posts

---

data/blog/2020/2020-03-09-transferring-zf-to-laminas.md

Hotfix: Removes duplicated subject in blog post

---

bootstrap/package-lock.json
bootstrap/package.json

See: https://blog.jquery.com/2020/04/10/jquery-3-5-0-released/

Update assets: jQuery 3.5.0

---

composer.json
composer.lock
config/config.php
src/Blog/ConfigProvider.php
src/ReleaseFeed/ConfigProvider.php
src/Security/Console/BuildCommand.php

- CommonMark TableExtension is now part of the main league/commonmark package.
- Diactoros 2.3 now provides dependency config for PSR-17 factories.

Update dependencies and make use of new features

---

templates/security/security.phtml

The href leads to a non existing page.

Remove trailing slash of the advisories href

---

templates/security/security.phtml

Adding url Helper as suggested in https://github.com/laminas/getlaminas.org/pull/43#discussion_r416855212

Use `url` helper for security links

---

bootstrap/package-lock.json
bootstrap/package.json
templates/layout/default.phtml

| QA            | yes
- jQuery 3.5.0 slim
- Bootstrap 4.4.1
- Popper.js 1.16.1
- FontAwesome 5.13.0
and fix in structure of layout - wrong closing tag for nav

Assets update

---

.platform.app.yaml

Fixes 404 on https://getlaminas.org/images/favicon/site.webmanifest

Fixes platform.sh configuration to allow expose webmanifest files

---

.docker/php/Dockerfile
.docker/php/php-entrypoint
composer.json
composer.lock
config/config.php
src/App/AbstractCollection.php
src/App/FrontMatter/Document.php
src/App/FrontMatter/DocumentInterface.php
src/App/FrontMatter/Parser.php
src/App/FrontMatter/ParserInterface.php
src/Blog/CreateBlogPostFromDataArray.php
src/Security/AdvisoryFactory.php
src/Security/Console/BuildCommand.php

| QA            | yes
- use spatie/yaml-front-matter instead of mnapoli/front-yaml
(so now we can use also symfony/yaml 5.0)
- add replace laminas/laminas-zendframework-bridge as we are not using
any not migrated components
- add platform configuration into composer.json
Replaces #45

QA: Update dependencies

---

bootstrap/package-lock.json
bootstrap/package.json

| QA            | yes
https://github.com/twbs/bootstrap/releases/tag/v4.5.0

Updates Bootstrap to version 4.5.0 (latest)

---

bootstrap/scss/_custom-variables.scss
bootstrap/scss/_support-banner.scss
bootstrap/scss/laminas.scss
src/App/ConfigProvider.php
templates/app/home-page.phtml
templates/app/support.phtml
templates/layout/default.phtml

Fixes #68 - Page for support of the project needed

---

bootstrap/scss/_support-banner.scss
templates/app/support.phtml

Fixes styles on sponsor links so the whole box is clickable

---

bootstrap/scss/_custom-styles.scss

issue https://github.com/laminas/getlaminas.org/issues/61
after fix
made indents like the cards below

update lead box for mobile

---

bootstrap/scss/_custom-styles.scss
templates/layout/default.phtml

issue https://github.com/laminas/getlaminas.org/issues/65
added an icon and slightly reduced padding so that everything would fit into the 1st line as it was

add github icon

---

bootstrap/scss/_custom-styles.scss

issue https://github.com/laminas/getlaminas.org/issues/67

fix teardrop card

---

templates/app/home-page.phtml

Align buttons in documentation cards to the bottom.
Screenshots comparison: http://www.framecompare.com/screenshotcomparison/KPKKWNNX

Update design of documentation cards

---

bootstrap/gulpfile.js
bootstrap/package-lock.json
bootstrap/package.json
bootstrap/scss/_custom-variables.scss
bootstrap/scss/_project.scss
bootstrap/scss/blocks/_footer.scss
bootstrap/scss/blocks/_support.scss
bootstrap/scss/laminas.scss
templates/layout/default.phtml
templates/partials/footer.phtml

Updates the footer of the website to adopt the design and layout from the documentation

---

README.md

Minor linting fixes to the readme to unblock renovate patches

README linting fixes

---

bootstrap/scss/_custom-styles.scss
templates/layout/default.phtml
templates/partials/navigation.phtml

Adds also missing link to security page with access to security advisories.

Adds dropdowns in navbar for Support and About with link to Security

---

bootstrap/scss/_custom-variables.scss
bootstrap/scss/laminas.scss
src/Blog/templates/list.phtml
src/Blog/templates/post.phtml
templates/app/home-page.phtml
templates/app/support.phtml
templates/community/participate.phtml
templates/partials/footer.phtml
templates/partials/navigation.phtml
templates/security/advisories.phtml
templates/security/advisory.phtml
templates/security/menu.phtml

Replaces the Font Awesome icon library with the Bootstrap Icons library and adds more icons to links and buttons.
This is the first step in switching to Bootstrap version 5.

Updated website icons and improved visual enhancements

---

data/blog/2024/2024-07-02-dotkernel-a-replacement-for-laminas-api-tools.md

branding issue fixed. It must be "Dotkernel" instead of "DotKernel"

---

templates/app/home-page.phtml

laminas api tools description change

---

.gitignore
bootstrap/scss/_custom-styles.scss
src/App/Console/WriteRepositoryData.php
templates/app/home-page.phtml
templates/app/packages-custom-properties.phtml

@arhimede Reverted home page text, added CSS "badges" instead of plain text for the properties on the listing page.
As discussed, packages marked as "is-published-component: false" are no longer logged, and empty properties are hidden (still logged if needed elsewhere).

Replaced static text with CSS badges on property listing page

---

bootstrap/scss/_custom-styles.scss
src/App/Console/WriteRepositoryData.php
templates/app/packages-custom-properties.phtml

@arhimede removed the "Is Deprecated" badge from the custom property listing page, minor design update and code refactoring

Removed "Is Deprecated" badge, minor refactoring

---

bootstrap/scss/_custom-styles.scss
src/App/ConfigProvider.php
src/App/Console/WriteRepositoryData.php
templates/app/packages-custom-properties.phtml
templates/partials/navigation.phtml

@arhimede layout and styling changes to the packages maintenance status page

packages maintenance status page updates

---

bootstrap/scss/_custom-styles.scss

@arhimede minor style update, separated packages' cards on the listing page

separation of package cards

---

.platform.app.yaml

@arhimede updated the platform.sh configuration

platform.sh config update

---

templates/partials/navigation.phtml

navbar button text change

---

templates/app/packages-custom-properties.phtml
templates/partials/footer.phtml
templates/partials/navigation.phtml

@arhimede moved the package status listing page link from navbar to the footer & added the requested text

package status listing page link & text change

---

templates/app/commercial-vendor-program.phtml

Missed the responsive layout upgrade for the cards on the commercial vendor page.

Fix commercial vendors layout for bootstrap 5

---

bootstrap/package-lock.json
composer.json
composer.lock
data/blog/2024/2024-09-26-using-laminas-continuous-delivery-and-deployment.md

new blog post: Using Laminas Continuous Delivery and Deployment

---

.platform/routes.yaml
data/blog/2024/2024-08-05-using-laminas-continuous-integration.md

@Xerkus @froschdesign 
This is supposed to fix the wrong url of the previous blog article.
The solution was to add a hardcoded rule in .htaccess file, maybe you have a different idea. 
Right now a link in latest blog article is broken....

Wrong pattern of an URL for a blog article

---

.github/workflows/pr-autocloser.yml
ADD_BLOG_ENTRY.md
README.md
bootstrap/package-lock.json
composer.json
composer.lock
src/Blog/templates/list.phtml

| Documentation | yes/no
| Bugfix        | yes/no
| BC Break      | yes/no
| New Feature   | yes/no
| RFC           | yes/no
| QA            | yes/no

add instructions to write blog 2

---

src/Blog/PlatesFunctionsDelegator.php

| Documentation |no
A fix for #240, where the blog post ID was never appended to the base url in `list.phtml`.
The `postUrl` plates function registered in `PlatesFunctionsDelegator` was always returning an empty string as `$this->template` was always null. If I'm not mistaken, that happened because of the way the function was registered, as the initial syntax was passing a Closure created before any template was set in `PlatesFunctionsDelegator`. 
Reverting to the traditional array syntax in the function registration seems to fix the issue by always providing access to the later set `template` property.

changed plates functions registration syntax

---

data/blog/2025/2025-02-03-summary-of-the-meeting-in-february-2025.md
data/blog/authors/bidi.yml

| Documentation | yes
| Bugfix        | no
Created summary for TSC feb 2025 based on the minutes of the meeting

Created summary for TSC feb 2025

---

data/blog/2025/2025-02-03-summary-of-the-meeting-in-february-2025.md

replace non-functional yet tag # with ###

fix ### markdowns tags

---

templates/layout/default.phtml

Replaced hardcoded OpenGraph url & title with current page data
Closes #253.

opengraph dynamic url and title

---

data/blog/2025/2025-06-06-laminas-mvc-is-retiring.md

it was easy for some to mistake the retiring as being more than just that of MVC (https://www.youtube.com/live/9MjcjThrOF0?si=qLJmPzyxtgTP5Exg&t=2406)
so a few highlights and a note might help readers understand what the article is referring to

updated content

---

config/autoload/home-page-content.global.php
data/blog/2020/2020-04-22-linux-foundation-launch.md
data/blog/2025/2025-02-03-summary-of-the-meeting-in-february-2025.md

fix dead links

---

bootstrap/scss/_custom-styles.scss
bootstrap/scss/_custom-variables.scss
templates/partials/navigation.phtml

Revised color variables for improved consistency and readability. Updated body and footer background color and added a new background style for articles. Removed redundant styles from the `main` element.
Closes #272

Updates the background colour to set a better focus

---

bootstrap/scss/_custom-styles.scss

Replaced redundant blockquote styling with a new `.blockquote` class. Added background color, padding, and adjusted styling for a cleaner appearance. Removed outdated blog-specific blockquote styles.
Closes #275

Refactor blockquote styles for improved readability and consistency

---

templates/security/advisory.phtml

Update security advisory template: improve back link with pagination styles

---

bootstrap/js/base.js
bootstrap/scss/_custom-styles.scss
psalm-baseline.xml
src/App/Enums/MaintenanceStatusEnum.php
src/App/Handler/MaintenanceOverviewHandler.php
src/App/Handler/MaintenanceOverviewHandlerFactory.php
templates/app/maintenance-overview.phtml

| Bugfix        | no
| RFC           | yes
Based on issue #280, added basic filtering by name and maintenance status.
Since there are relatively few packages, I went for a simple approach by filtering the array directly instead of a adding another sqlite db and all related logic. Let me know if that would be preferred though.
As for this array filtering version, it probably would be cleaner if the json file containing the data would be changed to remove the `property_name` and `value` keys which seem redundant, but I didn't want to add a BC break for the  [current json endpoint](https://getlaminas.org/maintenance-status).
```json
{
"laminas": [
{
"name": …
```

basic array filtering for maintenance status page

---

data/integration/integration-packages.json

[Naming](https://github.com/samsonasik/naming) is a library that has filter and validator for people name with multibyte string check support, extends the Laminas filter and validator, can be used in `laminas-form`, while also can be used as standalone.

Register samsonasik/naming to integration packages

---

src/Integration/templates/list.phtml

Redesigned the original "Add package" button on the Integrations page to match the design from #310 .
From:
To:

"add integration" button redesign

---

data/integration/integration-packages.json

Minor update to some `dotkernel` packages in the integrations json.

minor changes to dotkernel integrations data

---

data/integration/integration-packages.json

| Bugfix        | no
This adds https://github.com/settermjd/mezzio-twilio-integration to the list of integrations.

Add mezzio-twilio-integration to the list of integrations
